_format_version: "3.0"
_transform: true

services:
  - name: backend
    url: http://backend:8001
    routes:
      - name: revocation-demo
        paths:
          - /revocation-demo
        strip_path: false
        protocols: [ "http", "https" ]

      - name: public-hello
        paths:
          - /hello
        strip_path: false
        protocols: [ "http", "https" ]
        
      - name: api
        paths:
          - /api
        strip_path: false
        protocols: [ "http", "https" ]

      - name: hmac-api
        paths:
          - /hmac
        strip_path: true
        protocols: [ "http", "https" ]

plugins:
  - name: jwt
    route: api
    config:
      key_claim_name: kid           # lấy iss trong payload để tìm secret
      claims_to_verify: ["exp"]     # verify exp
      run_on_preflight: false
      secret_is_base64: false
  - name: hmac-signature
    route: hmac-api
    config:
      secrets: 
        client-1: super-secret-123
      max_clock_skew: 100          # 100s

consumers:
  - username: keycloak-issuer

jwt_secrets:
  - consumer: keycloak-issuer
    key: "D4GlALhttFw0QiIgfRX-rUZkQ-mHdkGlymLkHx_rjdo"   
    algorithm: "RS256"
    rsa_public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1IKCiIbrAIzlhs3CPlgk
      p2c18ZEGamL38tQS50ykumjEBMtcI+hq2+l1Tc0BqS+AlOJSUcroxRF6VMA2arRf
      TcM3irCKigg1VRmDNupaITJMtdlR6w9nC9HLNLBrleGQsg++USwkrIvk7i7O9NNY
      fHaBPa7hokilrd3sy0QjHmkTuwQTjQSWay4KFbeqn6i5OObEoombnP1/gsYPUHV7
      6VTYQYHEPK3bN4EYqBpXkdkHQ+D2ZfIG0DOYFMqcxLVOUcr7XvYG+C8seNHfKTku
      chaWij/ErMzDYbMThDyTEhkdnVKKIA1BJREsZuUfN+3NqInMb9lRtm+8E5iZqXfF
      QwIDAQAB
      -----END PUBLIC KEY-----

  - consumer: keycloak-issuer
    key: "5ajH2gHj0dyKxF7n1SuCepEcKu6tlF44g2H9C2SDucc"          
    algorithm: "RS256"
    rsa_public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAshShSdd5n/
      nUAgeAri86bDrHXNGx+CICM6cjOoW20mnI9lzf5H/KTjsqDLL0dAKf4L
      ZIOcHSuFmVwpsZLb/QwOMarKhdXQqLRDCJnnG/Kp916Lrf0AaHMyt
      LCQ8ZAjETZDG1XI0XpsY6DDJ23Bh5nN4q1V4C3fhysSWfZdC7kWLm
      AljWqf802omZwez5BhDiSdFOV7fz/oOnW4GhjQa8pPSiPnJDMxrt4uY
      +MgCEAh0G7+3MSzgmCJljx1VAb7Hl/oT+Mcif73/A6iznGX6ISlQN7PjA
      98R5XKMjKi+NPug8oaos1GbYBxVcRHC+EvL6dqQWnPpxGqPW9eGsj
      e6XBwIDAQAB
      -----END PUBLIC KEY-----
<<<<<<< HEAD
certificates:
  - cert: |
      -----BEGIN CERTIFICATE-----
      MIIBfjCCASOgAwIBAgIULt8vJ1SE9nsI0gPsPb83Ezl5njowCgYIKoZIzj0EAwIw
      FDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTI1MTIzMDE1MTIxOVoXDTI2MTIzMDE1
      MTIxOVowFDESMBAGA1UEAwwJbG9jYWxob3N0MFkwEwYHKoZIzj0CAQYIKoZIzj0D
      AQcDQgAE9CZZ1KFimD+0JdGTiUbDdXEdDPaNBQxZy9oyIFxv23SmLJSu232rgoqj
      CP2Zy/oeRSkHpyx62F47htaQngqJxaNTMFEwHQYDVR0OBBYEFG8dCZ29nRL7jwaN
      MagEvD/QpU46MB8GA1UdIwQYMBaAFG8dCZ29nRL7jwaNMagEvD/QpU46MA8GA1Ud
      EwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAPa6XlNqy2KCAhd1vE//4kEi
      ZR/xQHVv2z+BMGcJGDV/AiEA7xB5LN0a9U+5nduxVl5mDAcA3sFYhg3odtKOAalU
      VBM=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIIP1WVjLyPA9IUXb+kEayVR1ogBXqxUEg2HTYrDFjUkLoAoGCCqGSM49
      AwEHoUQDQgAE9CZZ1KFimD+0JdGTiUbDdXEdDPaNBQxZy9oyIFxv23SmLJSu232r
      goqjCP2Zy/oeRSkHpyx62F47htaQngqJxQ==
      -----END EC PRIVATE KEY-----
    snis: 
      - name: localhost
=======
>>>>>>> d9551c40136259999dfbd956f9f41f09b508db40
