_format_version: "3.0"
_transform: true

services:
  - name: backend
    url: http://backend:8001
    routes:
      - name: public-hello
        paths:
          - /hello
        strip_path: false
        protocols: [ "http", "https" ]
        
      - name: api
        paths:
          - /api
        strip_path: false
        protocols: [ "http", "https" ]

      - name: hmac-api
        paths:
          - /hmac
        strip_path: true
        protocols: [ "http", "https" ]

plugins:
  - name: jwt
    route: api
    config:
      key_claim_name: iss           # lấy iss trong payload để tìm secret
      claims_to_verify: ["exp"]     # verify exp
      run_on_preflight: false
      secret_is_base64: false
  - name: hmac-signature
    route: hmac-api
    config:
      secrets: 
        client-1: super-secret-123
      max_clock_skew: 100          # 100s

consumers:
  - username: keycloak-issuer

jwt_secrets:
  - consumer: keycloak-issuer
    key: "http://localhost:8080/realms/secure"   # TRÙNG với "iss" trong token
    algorithm: "RS256"
    rsa_public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1IKCiIbrAIzlhs3CPlgk
      p2c18ZEGamL38tQS50ykumjEBMtcI+hq2+l1Tc0BqS+AlOJSUcroxRF6VMA2arRf
      TcM3irCKigg1VRmDNupaITJMtdlR6w9nC9HLNLBrleGQsg++USwkrIvk7i7O9NNY
      fHaBPa7hokilrd3sy0QjHmkTuwQTjQSWay4KFbeqn6i5OObEoombnP1/gsYPUHV7
      6VTYQYHEPK3bN4EYqBpXkdkHQ+D2ZfIG0DOYFMqcxLVOUcr7XvYG+C8seNHfKTku
      chaWij/ErMzDYbMThDyTEhkdnVKKIA1BJREsZuUfN+3NqInMb9lRtm+8E5iZqXfF
      QwIDAQAB
      -----END PUBLIC KEY-----
